#!/usr/bin/env node

//plusplus is true because we use it in a for loop - no biggie.
/*jslint node: true, plusplus: true*/
"use strict";

//package declarations
var program =   require('commander');
var assert =    require('assert');

var currPage; //tracks which page of the message list we're on

//command line options
program
    .option('--sid <sid>',          'Your Twilio API Account SID')
    .option('--auth <authtoken>',   'Your Twilio API Auth Token')
    .parse(process.argv);

//sanity check command line input
assert.ok(program.sid, "SID is required");
assert.ok(program.auth, "Auth Token is required");

//build our client
var client = require('twilio')(program.sid, program.auth);

client.messages.list({}, function (err, data) {
    if (err) {
        console.log(err);
        console.log("This usually means your credentials are bad.");
        process.exit(1);
    }
    else{
        //loop through every page
        for (currPage = 0; currPage < data.num_pages; currPage++) {
            //retrieve the current page
            client.messages.list({Page: currPage}, function (err, data) {
                if (err) {
                    console.log("Message list error: " + err);
                }
                else{
                    //get a list of messages for the page (currPage)
                    data.messages.forEach(function (message) {
                        //delete the message itself
                        client.messages(message.sid).delete(function (err, data) {
                            if (err) {
                                console.log("Message deletion error: " + err.status + " -- " + err.message);
                            } else {
                                console.log("Deleted Message SID " + message.sid + " successfully.");
                            }
                        });
                    });
                }
            });
        }
    }
});
